project:
  type: book
  output-dir: docs

book:
  title: "RL-Course"
  reader-mode: true
  page-footer:
    left: |
      This notes for RL, are the first draft of for the course: From Markov Decision Processes to Reinforcement Learning
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover_RL.jpeg
  favicon: cover_RL.jpeg
  site-url: https://sauldiazinfante.github.io/RL-Course-2024-2/applications.html
  repo-url: https://github.com/SaulDiazInfante/RL-Course-2024-2.git
  #repo-branch: main
  #repo-actions: [edit, issue]
  comments:
    hypothesis:
      theme: clean
      openSidebar: True
  author: "Saúl Díaz Infante, David González Sánchez"
  date: "5/30/2024"
    
  chapters:
    - index.qmd
    - dynamic_programming.qmd
    - mdp.qmd
    - dp_rl.qmd
    - applications.qmd
    - references.qmd
bibliography: references.bib
format:
  html:
    theme: darkly
  pdf:
    documentclass: scrreprt



