project:
  type: book
  output-dir: docs

book:
  title: "From Markov Decision Processes to Reinforcement Learning with Python"
  page-navigation: true
  reader-mode: true
  page-footer:
    left: |
      This notes for RL, are the first draft of for the course: From Markov Decision Processes to Reinforcement Learning
#
  cover-image: cover_RL.jpeg
  favicon: cover_RL.jpeg
  site-url: https://sauldiazinfante.github.io/RL-Course-2024-2/
  repo-url: https://github.com/SaulDiazInfante/RL-Course-2024-2.git
  repo-branch: main
  repo-actions: [edit, issue]
  comments:
    hypothesis:
      theme: classic
      openSidebar: False
      
  author: "Saúl Díaz Infante, David González Sánchez"
  date: "5/30/2024"
  navbar:
    search: true
    downloads: [pdf]
  sidebar:
    pinned: true
    tools:
      - icon: save
#
  chapters:
    - index.qmd
    - ./01-introduction/general_intro.qmd
    - ./02-introductionToRL/intro.qmd
    - ./03-multiArmedBandit/multiarmed_bandits.qmd
    - ./04-finiteMDPs/mdp.qmd
    - ./05-dynamicProgramming/dp_rl.qmd
    - ./06-applications/applications.qmd
    - ./07-Project/project_proposal.qmd
    - ./08-Evaluation/rubric_evaluation.qmd
    - ./homeworks/home_works_list.qmd
    - ./homeworks/_hw_grades.qmd
    - references.qmd
#
filters:
  - quarto
  - section-bibliographies
  - pseudocode

section-bibiliograpies.cleanup-first: true
section-bibs-level: 1
link-citations: true
link-bibliography: true
bibliography: references.bib
reference-section-title: Refrences
citeproc: false
csl: elsevier-with-titles-alphabetical.csl

format:
  html:
    code-fold: true
    code-tools: true
    code-link: true
    code-line-numbers: true
    code-annotations: true
    theme:
      dark: darkly
      light: flatly
    callout-appearance: simple
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 3
    section-numbering: 1.1.a
    include-in-header:
      text: |
        <script>
        MathJax = {
          loader: {
            load: ['[tex]/boldsymbol']
          },
          tex: {
            tags: "all",
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true,
            processEnvironments: true,
            packages: {
              '[+]': ['boldsymbol']
            }
          }
        };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
    pdf:
        latex-auto-mk: false
        pdf-engine: latexmk
        pdf-engine-opts:
            - '-auxdir=custom-aux'
            - '-emulate-aux-dir'
        #documentclass: krantz
        include-in-header: latex/preamble.tex
        include-before-body: latex/before_body.tex
        include-after-body: latex/after_body.tex
        keep-tex: true
        callout-appearance: simple
 
jupyter: python3

execute:
  eval: false
  echo: false
  freeze: auto 
