---
title: "Project proposal"
author: "SDIV"
editor: visual
---

# Formulation and reinforcement learning solution to a problem

of a sequence of decisions.

# Bases

-   The sequence of decision must be based on a finite Markov decision Process.
    -   The space of states and action must to be finite and discrete.

## 

## Death line: December 08, 2024-23:59:00

## Sub-products

| **Death lines** |                             |
|-----------------|:---------------------------:|
| Stage 01        | **November 20, 2024-23:59** |
| Stage 02        | **December 15, 2024-23:59** |
| Stage 03        | **December 18, 2024-12:59** |

### Stage 01: Quarto book with MDP formulation

-   The page must encloses the report according to the template
    `rl_bookdown_prg.qmd`

    -   Introduction
    -   Formulation of the Mrakov decision process
    -   Model dynamics
    -   Description and justification of the Cost (reward)
    -   Justification of the actions

-   Must include

    -   Figures to illustrates the behavior of the regarding elements:

        1.  Policy
        2.  Reward
        3.  Value function eventuated for a one state-action and transition.
        4.  Environmental model

    -   References via bibtex.

    -   Output compilation for HTML and PDF formats.

    -   The compiled version has to be mounted ing GitHub or Quarto Pub

### Stage 02: Python code Implementation

-   Only code whit out running errors wold be accepted
-   Code must follows the style guide from PEP 08
-   All functions must include doc-strings
-   Extras:
-   Packing and Documentation `extra 200 xps`

### Stage 03: Video Presentation

A video mounted in you-tube of at most 20 min with results and insight of your
project

## Suggested project list:

1.  Reinforcement learning simulation of the TIC-TAC-TOE Game with SARSA or
    Q-learning Algorithms @Bilgin2020
2.  The movement of a Recycling Robot @Bilgin2020
3.  The replacement of a bus engine [@Rust1987] from [see pd.pdf, p.130
    @Starchursky2024]
4.  Optimal Inventories [see dp.pdf, p. 147 @Starchursky2024]
5.  Multi-Armed Bandits @Bilgin2020

## Project List

| Project | Author | Reference | GitHub Repo |
|--------------------|--------------------|--------------------|--------------------|
| Dynamic Portfolio Analysis | GABRIEL MIRANDA GAMEZ | [Sec. 4.3, @Bertsekas2005] | (gh_page)[<https://gabo-always-learning.quarto.pub/project-dpa/>] |
| Providing Tactical Advice in Professional Soccer | JOSE ITALO SANCHEZ BERMUDEZ | [@Decroos2020] | (gh_page)[<https://italosanchezb.github.io/Proyecto-Final-RL/>] |
| A MDP model for the collective behavior in vaccination campaigns | IRASEMA PEDROZA MEZA |  | (GitHub)<https://github.com/IrasemaPM/Proyecto_psi>|
| Modelo de inventario para alimentos pedecederos | DAVID PEÑA PERALTA | [@Starchursky2024] | (gh_page)[<https://dust1920.github.io/InventoryManagement/>] |
| A inventory model | JAZMIN SARAHI FLORES GOMEZ | [@levhari1982great] | (gh_page)[<https://flordejazmin.github.io/Proyectoinventario/>] |

: Project list {.striped .hover}

## Configuration to build with Spanish language

{{< include ./project_template.qmd >}}
